[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.4.2"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.21.9"

[[constraint]]
  name = "github.com/cenkalti/backoff"
  version = "3.0.0"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.3"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  name = "github.com/upmc-enterprises/registry-creds"
  version = "1.8.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  name = "k8s.io/client-go"
  version = "2.0.0"

[prune]
  go-tests = true
  unused-packages = true
